In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2
from PIL import Image
import os,sys
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

In [27]:
height = 300
width = 400
channels = 3
classes = 4
n_inputs = height * width*channels
label_encoder = LabelEncoder()

In [28]:
def load_image(height, width, channels, classes, folder_name):
    data, labels = [], []
    root_path = './' + folder_name + '/'
    print(root_path)
    dirs = os.listdir(root_path)
    for d in dirs:
        path = root_path + d
        img_count = len(os.listdir(path))
        for i in range(img_count):
            try: 
                img_path = str(path+'/{0}.jpeg').format(i)
                image = cv2.imread(img_path)
                image_from_array = Image.fromarray(image, 'RGB')
                size_image = image_from_array.resize((height, width))
                data.append(np.array(size_image))
                labels.append(d)
            except AttributeError:
                print(" ")

    Cells=np.array(data)
    labels=np.array(labels)

    s=np.arange(Cells.shape[0])
    np.random.seed(4)
    np.random.shuffle(s)
    Cells=Cells[s]
    labels=labels[s]

    X = Cells.astype('float32')/255
    y = label_encoder.fit_transform(labels)

    y = to_categorical(y, classes)

    return X, y

def data_processing(height, width, channel, classes):
    X_train, y_train = load_image(height, width, channel, classes, 'NonAugmentedTrain')
    X_val, y_val = load_image(height, width, channel, classes, 'ValData')
    return X_train, y_train, X_val, y_val

X_train, y_train, X_val, y_val = data_processing(height, 
                                                     width, 
                                                     channels, 
                                                     classes)
print(X_train)




./NonAugmentedTrain/
BacterialPneumonia
./NonAugmentedTrain/BacterialPneumonia
COVID-19
./NonAugmentedTrain/COVID-19
Normal
./NonAugmentedTrain/Normal
ViralPneumonia
./NonAugmentedTrain/ViralPneumonia
./ValData/
BacterialPneumonia
./ValData/BacterialPneumonia
COVID-19
./ValData/COVID-19
Normal
./ValData/Normal
ViralPneumonia
./ValData/ViralPneumonia
[[[[0.8392157  0.8392157  0.8392157 ]
   [0.83137256 0.83137256 0.83137256]
   [0.81960785 0.81960785 0.81960785]
   ...
   [0.74509805 0.74509805 0.74509805]
   [0.78039217 0.78039217 0.78039217]
   [0.78039217 0.78039217 0.78039217]]

  [[0.8392157  0.8392157  0.8392157 ]
   [0.83137256 0.83137256 0.83137256]
   [0.81960785 0.81960785 0.81960785]
   ...
   [0.7411765  0.7411765  0.7411765 ]
   [0.7882353  0.7882353  0.7882353 ]
   [0.79607844 0.79607844 0.79607844]]

  [[0.8352941  0.8352941  0.8352941 ]
   [0.827451   0.827451   0.827451  ]
   [0.8117647  0.8117647  0.8117647 ]
   ...
   [0.7254902  0.7254902  0.7254902 ]
   [0.8        

In [1]:
from GC_NET import get_flops, piecewise5, GC_Net
from keras.utils.generic_utils import get_custom_objects
from keras.layers import Activation

get_custom_objects().update({'piecewise5': Activation(piecewise5)})
input_shape=X_train.shape[1:]


Using TensorFlow backend.


AttributeError: module 'tensorflow' has no attribute 'get_default_graph'